project load build

flow run /SCVerify/launch_make ./scverify/Verify_concat_sim_rtl_v_ncsim.mk {} SIMTOOL=ncsim simgui

# naming rules for the verification files generated by Catapult:
#  Verify_<netlist-leaf-name>_<language>_<simulator>.mk
#  Here, <netlist-leaf-name> is "concat_sim_rtl"
#  <language> is "v"
