build_dir: 2-info
build_id: '2'
commands:
- echo "Design name      -- GcdUnit"
- echo "Clock period     -- 2.0"
- echo "ADK              -- freepdk-45nm"
- echo "ADK view         -- view-standard"
- echo
- echo "Constructed from -- /home/users/ctorng/work/cc/ee272-hw5/GcdUnit/design/construct.py"
- echo
edges_i: {}
edges_o: {}
name: info
parameters:
  adk: freepdk-45nm
  adk_view: view-standard
  clock_period: 2.0
  construct_path: /home/users/ctorng/work/cc/ee272-hw5/GcdUnit/design/construct.py
  design_name: GcdUnit
source: /home/users/ctorng/work/cc/mflowgen/steps/info
