build_dir: 3-rtl
build_id: '3'
commands:
- 'true'
edges_i: {}
edges_o:
  design.v:
  - f: design.v
    step: 4-synopsys-dc-synthesis
name: rtl
outputs:
- design.v
source: /home/users/ctorng/work/cc/ee272-hw5/GcdUnit/design/rtl
